---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  # POSTGRES_PASSWORD: testpassword
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Secret
data:
  password: dGVzdHBhc3N3b3JkCg==
  secret_key: c3VwZXJzZWNyZXRrZXkK
metadata:
  name: postgres-config
type: Opaque
---
# REDMINE
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-config
  labels:
    app: redmine
data:
  REDMINE_DB_POSTGRES: database
  REDMINE_DB_DATABASE: testdatabase
  REDMINE_DB_USERNAME: testuser
  # REDMINE_DB_PASSWORD: testpassword
