---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
      - image: redmine:4.1.1
        name: redmine
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: redmine-config
        env:
        - name: REDMINE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: password
        - name: REDMINE_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: secret_key 
        # readinessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 3000
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 60
        # livenessProbe:
        #   failureThreshold: 3
        #   httpGet:
        #     path: /
        #     port: 3000
        #   periodSeconds: 10
        #   successThreshold: 1
        #   timeoutSeconds: 60
        #   initialDelaySeconds: 10
